name: Composite addition action
description: Add up to four numbers
author: 'fiona.klute@gmx.de'

inputs:
  num1:
    description: 'Summand one'
    required: yes
  num2:
    description: 'Summand two'
    required: no
    default: 0
  num3:
    description: 'Summand three'
    required: no
    default: 0
  num4:
    description: 'Summand four'
    required: no
    default: 0

outputs:
  sum:
    description: Sum of the input numbers
    value: ${{ steps.calculate-sum.outputs.sum }}

runs:
  using: composite
  steps:
    - run: |
        echo "::group::Show INPUT vars"
        for i in INPUT_NUM1 INPUT_NUM2 INPUT_NUM3 INPUT_NUM4; do
            echo "${i} = ${!i}"
        done
        echo "::endgroup::"
      shell: bash
    - run: |
        print('::group::Add numbers')
        import os
        nums = []
        for i in range(1,5):
            nums.append(int(os.environ.get(f'INPUT_NUM{i}')))
        with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
            print(f'sum={sum(nums)}', file=fh)
        print('::endgroup::')
      id: calculate-sum
      shell: python3 {0}
      env:
        INPUT_NUM1: ${{ inputs.num1 }}
        INPUT_NUM2: ${{ inputs.num2 }}
        INPUT_NUM3: ${{ inputs.num3 }}
        INPUT_NUM4: ${{ inputs.num4 }}
