name: Multiline output
on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: define list
        id: files
        run: |
          echo "::set-output name=list::test.tex \"test 2.tex\""
      - name: show space separated list
        run: echo ${{ steps.files.outputs.list }}
      - name: make list newline separated
        id: lines
        run: |
          import os
          import shlex
          # %0A is a URL-encoded newline (\n)
          output = '%0A'.join(shlex.split(os.environ['INPUT_LIST']))
          print(f'::set-output name=list::{output}')
        shell: python3 {0}
        env:
          INPUT_LIST: ${{ steps.files.outputs.list }}
      - name: show line separated list
        run: echo "${LIST}"
        env:
          LIST: ${{ steps.lines.outputs.list }}
