name: Multiline output
on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: define list
        id: files
        run: |
          echo "list=test.tex \"test 2.tex\"" >>${GITHUB_OUTPUT}
      - name: show space separated list
        run: echo ${{ steps.files.outputs.list }}
      - name: make list newline separated
        id: lines
        run: |
          import os
          import shlex
          # %0A is a URL-encoded newline (\n)
          output = '%0A'.join(shlex.split(os.environ['INPUT_LIST']))
          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
              print(f'list={output}', file=fh)
        shell: python3 {0}
        env:
          INPUT_LIST: ${{ steps.files.outputs.list }}
      - name: show line separated list
        run: echo "${LIST}"
        env:
          LIST: ${{ steps.lines.outputs.list }}
