name: Wiki automation test
on:
  push:
    paths:
      - '.github/workflows/wiki-bot.yaml'
      - 'wiki-bot.bash'
    branches-ignore:
      - 'dependabot/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    name: Wiki access
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki
      - run: cat wiki/Home.md
      - name: Update Bot.md
        run: bash wiki-bot.bash wiki/
      - name: Commit and push Bot.md
        working-directory: wiki
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add Bot.md
          git commit -m "Wiki bot run!"
          git push
