name: Wiki automation test
on:
  push:
    paths:
      - '.github/workflows/wiki-bot.yaml'
      - 'wiki-bot.bash'
  workflow_dispatch:

jobs:
  test:
    name: Wiki access
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki
      - run: cat wiki/Home.md
      - name: Update Bot.md
        run: bash wiki-bot.bash wiki/
      - name: Commit and push Bot.md
        working-directory: wiki
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add Bot.md
          git commit -m "Wiki bot run!"
          git push
